name: 'Cache nix too'
description: 'Cache artifacts like dependencies and build outputs to improve workflow execution time'
author: 'GitHub'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache and restore'
    required: false
    default: ""
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.'
    required: false
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms'
    default: 'false'
    required: false
  fail-on-cache-miss:
    description: 'Fail the workflow if cache entry is not found'
    default: 'false'
    required: false
  lookup-only:
    description: 'Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache'
    default: 'false'
    required: false
  macos-gc-enabled:
    description: 'When `true`, enables conditional garbage collection before saving a cache on macOS runners.'
    required: false
    default: "false"
  macos-max-store-size:
    description: 'Maximum Nix store size in bytes on macOS runners. Requires `macos-gc-enabled: true`.'
    required: false
  linux-gc-enabled:
    description: 'When `true`, enables conditional garbage collection before saving a cache on Linux runners.'
    required: false
    default: "false"
  linux-max-store-size:
    description: 'Maximum Nix store size in bytes on Linux runners. Requires `linux-gc-enabled: true`.'
    required: false
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: success()
branding:
  icon: 'archive'
  color: 'gray-dark'
