jobs:
  test:
    name: Nix CI
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            keep-outputs = true

      - name: Restore and cache Nix store
        if: ${{ matrix.do-cache }}
        uses: ./.
        with:
          linux-gc-enabled: true
          # more than necessary
          linux-max-store-size: 8000000000
          macos-gc-enabled: true
          # less than necessary
          macos-max-store-size: 8000000
          key: cache-${{ matrix.os }}-${{ hashFiles('.github/workflows/ci.yaml') }}
          restore-keys: |
            cache-${{ matrix.os }}

      # Uncomment to debug this job
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Show profile
        run: nix profile list

      - name: Lock nixpkgs
        run: |
          nix registry add nixpkgs github:NixOS/nixpkgs/5daaa32204e9c46b05cd709218b7ba733d07e80c
          nix profile install $(nix flake archive nixpkgs --json | jq -r '.path')

      - name: Show profile
        run: nix profile list

      - name: Run commands
        run: |
          nix run nixpkgs#hello
          nix profile install nixpkgs#hello
          
          # nix profile install nixpkgs#cachix
          
          # nix profile install nixpkgs#nixpkgs-fmt
          # nix profile install nixpkgs#alejandra
          
          # nix profile install nixpkgs#nixd
          
          # nix profile install nixpkgs#ghc
          # nix profile install nixpkgs#haskell-language-server
          
          # nix profile install nixpkgs#purescript
          
          # nix profile install nixpkgs#nodejs_18

      - name: Show profile
        run: nix profile list

    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-20.04
          - ubuntu-22.04
        do-cache:
          - true
          # - false

  remove-old-data:
    name: Remove old data
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.4
        with:
          retain_days: 7
          keep_minimum_runs: 7
      - uses: deemp/purge-cache@v1
        with:
          # 3 days
          debug: true
          max-age: 259200
        
name: Nix CI
"on":
  push: {}
  pull_request: {}
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
